#define STACK_SIZE 200*32
#define SLEEP_TIME 20
#define BUTTON_GPIO GPIO_NUM_2

#define CODING_RATE 7
#define BANDWIDTH 7
#define SPREAD_FACTOR 11

#define GLOBAL_TIMEOUT 60
#define LOCAL_TIMEOUT 2

#define TOWER_NUMBER 1
